In [2]:
import numpy as np

In [ ]:
arr=np.random.random((3,4))

In [4]:
np.arange(1,100,8)     # n0.s btw 1 - 100 with the gap of 8 (3rd pramtr)      .arrange(start, end , gap)

array([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97])

In [5]:
np.linspace(1,10,5)   # (3rd pramtr) 5 no.s btw 1(1st pramtr) to 10(2nd pramtr) with same gap    .linespace(start , end , total no.s)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr


array([[0.65212524, 0.0383785 , 0.26643751, 0.21482247],
       [0.08279613, 0.77796227, 0.78979238, 0.08543572],
       [0.47150626, 0.68621129, 0.7058172 , 0.23116622]])

In [ ]:
np.reshape(arr,(6,2))

array([[0.65212524, 0.0383785 ],
       [0.26643751, 0.21482247],
       [0.08279613, 0.77796227],
       [0.78979238, 0.08543572],
       [0.47150626, 0.68621129],
       [0.7058172 , 0.23116622]])

In [ ]:
arr

array([[0.65212524, 0.0383785 , 0.26643751, 0.21482247],
       [0.08279613, 0.77796227, 0.78979238, 0.08543572],
       [0.47150626, 0.68621129, 0.7058172 , 0.23116622]])

In [ ]:
arr.max(axis=0)#max for each col

array([0.65212524, 0.77796227, 0.78979238, 0.23116622])

In [ ]:
arr.max(axis=1)#max for each row

array([0.65212524, 0.78979238, 0.7058172 ])

In [ ]:
arr.min(axis=0)#max for each col

array([0.08279613, 0.0383785 , 0.26643751, 0.08543572])

In [ ]:
arr.min(axis=1)#min for each row

array([0.0383785 , 0.08279613, 0.23116622])

In [ ]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is DCC5-62E7

 Directory of C:\Users\rashp

01/08/2023  02:35 AM    <DIR>          .
01/07/2023  02:27 PM    <DIR>          ..
01/08/2023  04:12 AM    <DIR>          .conda
01/07/2023  03:19 PM                25 .condarc
01/07/2023  03:19 PM    <DIR>          .continuum
01/08/2023  02:13 AM    <DIR>          .ipynb_checkpoints
01/07/2023  07:56 PM    <DIR>          .ipython
01/07/2023  03:36 PM    <DIR>          .jupyter
01/07/2023  03:20 PM    <DIR>          anaconda3
01/07/2023  02:45 PM    <DIR>          Contacts
01/08/2023  12:12 AM             4,108 create bulk directories.ipynb
01/08/2023  12:10 AM    <DIR>          Documents
01/07/2023  09:30 PM    <DIR>          Downloads
01/07/2023  02:45 PM    <DIR>          Favorites
01/07/2023  02:45 PM    <DIR>          Links
01/07/2023  02:45 PM    <DIR>          Music
01/08/2023  01:00 AM    <DIR>          OneDrive
01/07/2023  02:45 PM    <DIR>          Saved Games
01/07/2023  03:42

In [ ]:
import os

In [ ]:
os.chdir('course_data_file')


In [ ]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is DCC5-62E7

 Directory of C:\Users\rashp\course_data_file

01/08/2023  04:38 AM    <DIR>          .
01/08/2023  04:21 PM    <DIR>          ..
01/08/2023  04:22 AM         1,360,155 datafile.csv
01/08/2023  04:15 AM         1,360,155 datafile.txt
               2 File(s)      2,720,310 bytes
               2 Dir(s)  386,100,436,992 bytes free


In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('datafile.csv')

In [ ]:
data['App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...                        
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [ ]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [ ]:
df = data.dropna()

In [ ]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [ ]:
df1 = pd.DataFrame(data)

In [ ]:
df1

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0   
1         3.9     967                 14M     500,000+  Free     0   
2         4.7   87510                8.7M   5,000,000+  Free     0   
3         4.5  215644                 25M  50,000,000+  Free     0   
4         4.3     967                2.8M     100,000+  Free     0   
...       ...     ...                 ...          ...   ...   ...   
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10838       Everyone                    Medical  January 20, 2017   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  
0                   1.0.0        4.0.3 and up  
1                   2.0.0        4.0.3 and up  
2                   1.2.4        4.0.3 and up  
3      Varies with device          4.2 and up  
4                     1.1          4.4 and up  
...                   ...                 ...  
10836                1.48          4.1 and up  
10837                 1.0          4.1 and up  
10838                 1.0          2.2 and up  
10839  Varies with device  Varies with device  
10840  Varies with device  Varies with device  

[10841 rows x 13 columns]

In [ ]:
df2 = df1['Category'].unique()

In [ ]:
for i in df2:
    print(i)

ART_AND_DESIGN
AUTO_AND_VEHICLES
BEAUTY
BOOKS_AND_REFERENCE
BUSINESS
COMICS
COMMUNICATION
DATING
EDUCATION
ENTERTAINMENT
EVENTS
FINANCE
FOOD_AND_DRINK
HEALTH_AND_FITNESS
HOUSE_AND_HOME
LIBRARIES_AND_DEMO
LIFESTYLE
GAME
FAMILY
MEDICAL
SOCIAL
SHOPPING
PHOTOGRAPHY
SPORTS
TRAVEL_AND_LOCAL
TOOLS
PERSONALIZATION
PRODUCTIVITY
PARENTING
WEATHER
VIDEO_PLAYERS
NEWS_AND_MAGAZINES
MAPS_AND_NAVIGATION
1.9


In [ ]:
# #dealing with null..not simply removing it.
# sklearn   from sklearn.impute import simpleImputer

In [ ]:
df = pd.read_csv('datafile.csv')

In [ ]:
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0   
1         3.9     967                 14M     500,000+  Free     0   
2         4.7   87510                8.7M   5,000,000+  Free     0   
3         4.5  215644                 25M  50,000,000+  Free     0   
4         4.3     967                2.8M     100,000+  Free     0   
...       ...     ...                 ...          ...   ...   ...   
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10838       Everyone                    Medical  January 20, 2017   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  
0                   1.0.0        4.0.3 and up  
1                   2.0.0        4.0.3 and up  
2                   1.2.4        4.0.3 and up  
3      Varies with device          4.2 and up  
4                     1.1          4.4 and up  
...                   ...                 ...  
10836                1.48          4.1 and up  
10837                 1.0          4.1 and up  
10838                 1.0          2.2 and up  
10839  Varies with device  Varies with device  
10840  Varies with device  Varies with device  

[10841 rows x 13 columns]

In [ ]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')


In [ ]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [ ]:
imputer.fit(df.iloc[:,2:3])

SimpleImputer()

In [ ]:
df.iloc[:,2:3] = imputer.transform(df.iloc[:,2:3])

In [ ]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

         Rating Reviews                Size     Installs  Type Price  \
0      4.100000     159                 19M      10,000+  Free     0   
1      3.900000     967                 14M     500,000+  Free     0   
2      4.700000   87510                8.7M   5,000,000+  Free     0   
3      4.500000  215644                 25M  50,000,000+  Free     0   
4      4.300000     967                2.8M     100,000+  Free     0   
...         ...     ...                 ...          ...   ...   ...   
10836  4.500000      38                 53M       5,000+  Free     0   
10837  5.000000       4                3.6M         100+  Free     0   
10838  4.193338       3                9.5M       1,000+  Free     0   
10839  4.500000     114  Varies with device       1,000+  Free     0   
10840  4.500000  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10838       Everyone                    Medical  January 20, 2017   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  
0                   1.0.0        4.0.3 and up  
1                   2.0.0        4.0.3 and up  
2                   1.2.4        4.0.3 and up  
3      Varies with device          4.2 and up  
4                     1.1          4.4 and up  
...                   ...                 ...  
10836                1.48          4.1 and up  
10837                 1.0          4.1 and up  
10838                 1.0          2.2 and up  
10839  Varies with device  Varies with device  
10840  Varies with device  Varies with device  

[10829 rows x 13 columns]

In [ ]:
# to deal with null by imputing mean/median/mode values on null
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer    #to compute fit and transform the values and apply *mean* on them or *median* or *most frequent*

df = pd.read_csv('datafile.csv')
#df.isnull().sum()                    #used to check and give no of null values in each categories

impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')

impute.fit(df.iloc[ : , 2:3 ])


df.iloc[:,2:3] = impute.transform(df.iloc[ : , 2:3 ])  #to get values of rating locating at col 2nd


df.isnull().sum()

df = df.dropna()  #to drop is null found

df.isnull().sum()

df.head(20)  #standard 5..or given user defiend value


App        Category  Rating  \
0      Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                 Coloring book moana  ART_AND_DESIGN     3.9   
2   U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                               Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4               Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   
5                          Paper flowers instructions  ART_AND_DESIGN     4.4   
6             Smoke Effect Photo Maker - Smoke Editor  ART_AND_DESIGN     3.8   
7                                    Infinite Painter  ART_AND_DESIGN     4.1   
8                                Garden Coloring Book  ART_AND_DESIGN     4.4   
9                       Kids Paint Free - Drawing Fun  ART_AND_DESIGN     4.7   
10                            Text on Photo - Fonteee  ART_AND_DESIGN     4.4   
11            Name Art Photo Editor - Focus n Filters  ART_AND_DESIGN     4.4   
12                     Tattoo Name On My Photo Editor  ART_AND_DESIGN     4.2   
13                              Mandala Coloring Book  ART_AND_DESIGN     4.6   
14    3D Color Pixel by Number - Sandbox Art Coloring  ART_AND_DESIGN     4.4   
16       Photo Designer - Write your name with shapes  ART_AND_DESIGN     4.7   
17                           350 Diy Room Decor Ideas  ART_AND_DESIGN     4.5   
18                      FlipaClip - Cartoon animation  ART_AND_DESIGN     4.3   
19                                       ibis Paint X  ART_AND_DESIGN     4.6   
20                        Logo Maker - Small Business  ART_AND_DESIGN     4.0   

   Reviews  Size     Installs  Type Price Content Rating  \
0      159   19M      10,000+  Free     0       Everyone   
1      967   14M     500,000+  Free     0       Everyone   
2    87510  8.7M   5,000,000+  Free     0       Everyone   
3   215644   25M  50,000,000+  Free     0           Teen   
4      967  2.8M     100,000+  Free     0       Everyone   
5      167  5.6M      50,000+  Free     0       Everyone   
6      178   19M      50,000+  Free     0       Everyone   
7    36815   29M   1,000,000+  Free     0       Everyone   
8    13791   33M   1,000,000+  Free     0       Everyone   
9      121  3.1M      10,000+  Free     0       Everyone   
10   13880   28M   1,000,000+  Free     0       Everyone   
11    8788   12M   1,000,000+  Free     0       Everyone   
12   44829   20M  10,000,000+  Free     0           Teen   
13    4326   21M     100,000+  Free     0       Everyone   
14    1518   37M     100,000+  Free     0       Everyone   
16    3632  5.5M     500,000+  Free     0       Everyone   
17      27   17M      10,000+  Free     0       Everyone   
18  194216   39M   5,000,000+  Free     0       Everyone   
19  224399   31M  10,000,000+  Free     0       Everyone   
20     450   14M     100,000+  Free     0       Everyone   

                       Genres        Last Updated         Current Ver  \
0                Art & Design     January 7, 2018               1.0.0   
1   Art & Design;Pretend Play    January 15, 2018               2.0.0   
2                Art & Design      August 1, 2018               1.2.4   
3                Art & Design        June 8, 2018  Varies with device   
4     Art & Design;Creativity       June 20, 2018                 1.1   
5                Art & Design      March 26, 2017                 1.0   
6                Art & Design      April 26, 2018                 1.1   
7                Art & Design       June 14, 2018            6.1.61.1   
8                Art & Design  September 20, 2017               2.9.2   
9     Art & Design;Creativity        July 3, 2018                 2.8   
10               Art & Design    October 27, 2017               1.0.4   
11               Art & Design       July 31, 2018              1.0.15   
12               Art & Design       April 2, 2018                 3.8   
13               Art & Design       June 26, 2018               1

In [ ]:
#this to deal full data's null value with imputing mode(most frequent) at d place of null

import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer    #to compute fit and transform the values and apply *mean* on them or *median* or *most frequent*

df = pd.read_csv('datafile.csv')
#df
df.isnull().sum()                    #used to check and give no of null values in each categories

impute = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')

impute.fit(df.iloc[ : , : ])


df.iloc[:,:] = impute.transform(df.iloc[ : , : ])  #to get values of rating locating at col 2nd


df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [ ]:
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0   
1         3.9     967                 14M     500,000+  Free     0   
2         4.7   87510                8.7M   5,000,000+  Free     0   
3         4.5  215644                 25M  50,000,000+  Free     0   
4         4.3     967                2.8M     100,000+  Free     0   
...       ...     ...                 ...          ...   ...   ...   
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     4.4       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10838       Everyone                    Medical  January 20, 2017   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  
0                   1.0.0        4.0.3 and up  
1                   2.0.0        4.0.3 and up  
2                   1.2.4        4.0.3 and up  
3      Varies with device          4.2 and up  
4                     1.1          4.4 and up  
...                   ...                 ...  
10836                1.48          4.1 and up  
10837                 1.0          4.1 and up  
10838                 1.0          2.2 and up  
10839  Varies with device  Varies with device  
10840  Varies with device  Varies with device  

[10841 rows x 13 columns]

#to check what all apps are free ..there name and count and should of same category and rating should be 4.5 and more


In [ ]:
df1 = df.values
#df[0]


In [ ]:
df1[0]

array(['Photo Editor & Candy Camera & Grid & ScrapBook', 'ART_AND_DESIGN',
       4.1, '159', '19M', '10,000+', 'Free', '0', 'Everyone',
       'Art & Design', 'January 7, 2018', '1.0.0', '4.0.3 and up'],
      dtype=object)

In [ ]:
c=0
print('--'*20)
for i in df1:
    if i[1] == 'ART_AND_DESIGN' and i[2] >=4.5  and i[6] == 'Free':
        c +=1
        print(i[0])
        print('-'*10)
print('--'*20)
print('There are {c} app of category ART_AND_DESIGN and also free and of rating = or more than 4.5')

----------------------------------------
U Launcher Lite – FREE Live Cool Themes, Hide Apps
----------
Sketch - Draw & Paint
----------
Kids Paint Free - Drawing Fun
----------
Mandala Coloring Book
----------
Photo Designer - Write your name with shapes
----------
350 Diy Room Decor Ideas
----------
ibis Paint X
----------
Superheroes Wallpapers | 4K Backgrounds
----------
HD Mickey Minnie Wallpapers
----------
Harley Quinn wallpapers HD
----------
Colorfit - Drawing & Coloring
----------
Anime Manga Coloring Book
----------
I Creative Idea
----------
UNICORN - Color By Number & Pixel Art Coloring
----------
PIP Camera - PIP Collage Maker
----------
Sad Poetry Photo Frames 2018
----------
Canva: Poster, banner, card maker & graphic design
----------
Install images with music to make video without Net - 2018
----------
Cardi B Wallpaper
----------
X Launcher: With OS11 Style Theme & Control Center
----------
AJ Styles HD Wallpapers
----------
Fantasy theme dark bw black building
------

In [ ]:
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

# Easy method to do above task


In [ ]:
df_ct = df[df['Category'] == 'ART_AND_DESIGN'] #df_ct =category which i want


In [ ]:
df_rt = df_ct[df_ct['Rating'] >= 4.5] #df_rt is all the apps having category and rating which i want 

In [ ]:
df_final = df_rt[df_rt['Type'] == 'Free']

In [ ]:
df_final #all the apps of ART_AND_DESIGN ,free and rating =>4.5

App        Category  \
2     U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN   
3                                 Sketch - Draw & Paint  ART_AND_DESIGN   
9                         Kids Paint Free - Drawing Fun  ART_AND_DESIGN   
13                                Mandala Coloring Book  ART_AND_DESIGN   
16         Photo Designer - Write your name with shapes  ART_AND_DESIGN   
17                             350 Diy Room Decor Ideas  ART_AND_DESIGN   
19                                         ibis Paint X  ART_AND_DESIGN   
22              Superheroes Wallpapers | 4K Backgrounds  ART_AND_DESIGN   
24                          HD Mickey Minnie Wallpapers  ART_AND_DESIGN   
25                           Harley Quinn wallpapers HD  ART_AND_DESIGN   
26                        Colorfit - Drawing & Coloring  ART_AND_DESIGN   
32                            Anime Manga Coloring Book  ART_AND_DESIGN   
34                                      I Creative Idea  ART_AND_DESIGN   
36       UNICORN - Color By Number & Pixel Art Coloring  ART_AND_DESIGN   
38                       PIP Camera - PIP Collage Maker  ART_AND_DESIGN   
41                         Sad Poetry Photo Frames 2018  ART_AND_DESIGN   
45    Canva: Poster, banner, card maker & graphic de...  ART_AND_DESIGN   
46    Install images with music to make video withou...  ART_AND_DESIGN   
3982                                  Cardi B Wallpaper  ART_AND_DESIGN   
4749  X Launcher: With OS11 Style Theme & Control Ce...  ART_AND_DESIGN   
5254                            AJ Styles HD Wallpapers  ART_AND_DESIGN   
6930               Fantasy theme dark bw black building  ART_AND_DESIGN   
8888            Spring flowers theme couleurs d t space  ART_AND_DESIGN   

      Rating Reviews  Size     Installs  Type Price Content Rating  \
2        4.7   87510  8.7M   5,000,000+  Free     0       Everyone   
3        4.5  215644   25M  50,000,000+  Free     0           Teen   
9        4.7     121  3.1M      10,000+  Free     0       Everyone   
13       4.6    4326   21M     100,000+  Free     0       Everyone   
16       4.7    3632  5.5M     500,000+  Free     0       Everyone   
17       4.5      27   17M      10,000+  Free     0       Everyone   
19       4.6  224399   31M  10,000,000+  Free     0       Everyone   
22       4.7    7699  4.2M     500,000+  Free     0   Everyone 10+   
24       4.7     118   23M      50,000+  Free     0       Everyone   
25       4.8     192  6.0M      10,000+  Free     0       Everyone   
26       4.7   20260   25M     500,000+  Free     0       Everyone   
32       4.5    5035   11M     100,000+  Free     0       Everyone   
34       4.7     353  4.2M      10,000+  Free     0           Teen   
36       4.7    8145   24M     500,000+  Free     0       Everyone   
38       4.7     158   11M      10,000+  Free     0       Everyone   
41       4.5     176   10M     100,000+  Free     0       Everyone   
45       4.7  174531   24M  10,000,000+  Free     0       Everyone   
46       4.6    1070   26M     100,000+  Free     0       Everyone   
3982     4.8     253  3.7M      50,000+  Free     0       Everyone   
4749     4.7    5754  4.4M     100,000+  Free     0       Everyone   
5254     4.8      48   25M       5,000+  Free     0       Everyone   
6930     4.8      41  1.9M       5,000+  Free     0       Everyone   
8888     5.0       1  2.9M         100+  Free     0       Everyone   

                       Genres       Last Updated         Current Ver  \
2                Art & Design     August 1, 2018               1.2.4   
3                Art & Design       June 8, 2018  Varies with device   
9     Art & Design;Creativity       July 3, 2018                 2.8   
13               Art & Design      June 26, 2018               1.0.4   
16               Art & Design      July 31, 2018                 3.1   
17               Art & Design   November 7, 2017                 1.0   
19               Art & Design      July 30, 2018               5.5

# Groupby usage for more complexicity


### Q1 Which category having max  avg rating

In [ ]:
df['Category'].unique()#in sb k ratings k avg nikalna h


array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [ ]:
df[df['Category'] == '1.9']

App Category  Rating Reviews  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0    3.0M   

         Size Installs Type     Price Content Rating             Genres  \
10472  1,000+     Free    0  Everyone       Everyone  February 11, 2018   

      Last Updated Current Ver Android Ver  
10472       1.0.19  4.0 and up  4.1 and up

In [ ]:
df.groupby('Category').mean()['Rating'].sort_values(ascending = True)

Category
DATING                  4.042308
MAPS_AND_NAVIGATION     4.084672
VIDEO_PLAYERS           4.092571
TOOLS                   4.093001
ENTERTAINMENT           4.126174
TRAVEL_AND_LOCAL        4.145349
LIFESTYLE               4.149215
COMICS                  4.163333
FINANCE                 4.163388
NEWS_AND_MAGAZINES      4.179505
COMMUNICATION           4.195349
FOOD_AND_DRINK          4.200000
PHOTOGRAPHY             4.203284
FAMILY                  4.215974
BUSINESS                4.216522
AUTO_AND_VEHICLES       4.220000
HOUSE_AND_HOME          4.225000
LIBRARIES_AND_DEMO      4.230588
MEDICAL                 4.240605
PRODUCTIVITY            4.243868
SPORTS                  4.253385
WEATHER                 4.257317
SHOPPING                4.271538
SOCIAL                  4.273220
GAME                    4.290997
HEALTH_AND_FITNESS      4.292962
BEAUTY                  4.303774
PARENTING               4.316667
PERSONALIZATION         4.348724
BOOKS_AND_REFERENCE     4.358442
A